spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/study_db
    username: postgres
    password:
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  doc:
    api-docs:
      path: /api-docs